openapi: 3.0.3
info:
  title: Core
  description: |
    The schemas related to n1-beneficiary-service core
  termsOfService: https://www.nium.com
  contact:
    name: Beneficiary Service
    url: https://www.nium.com
    email: core-dev@nium.com
  license:
    name: Copyright (c) 2024 NIUM
  version: 3.0.0
servers:
  - url: https://gatewaysandbox.nium.com/beneficiary-service/
    description: QA server url
paths: {}
components:
  schemas:
    CountryCode:
      title: CountryCode
      pattern: "^[A-Z]{2}$"
      type: string
      description: A 2-letter ISO country code.
      example: US
    CurrencyCode:
      pattern: "^[a-zA-Z]{3}$"
      type: string
      description: A 3-letter ISO-4217 currency code.
      example: USD
    Email:
      title: Email
      pattern: "^([a-zA-Z0-9+_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,63})$"
      type: string
      description: An email address
    ContactNumber:
      title: ContactNumber
      pattern: "^\\+[0-9]{1,17}$"
      type: string
      description: A contact number
      example: "+911234567890"
    PostalCode:
      title: PostalCode
      pattern: "^[0-9]{0,15}$"
      type: string
      description: An address postal or zip code.
      example: "94560"
    AddressState:
      title: AddressState
      pattern: "^[A-Za-z0-9\\s-.():_/]{1,50}$"
      type: string
      description: An address state
      example: "California"
    AddressCity:
      title: AddressCity
      pattern: "^[A-Za-z0-9\\s-.():_/]{1,50}$"
      type: string
      description: An address city
      example: "Newark"
    AddressType:
      title: AddressType
      type: string
      description: A possible address type
      default: billing
      enum:
        - mailing
        - billing
    CoreApiHashId:
      title: CoreApiHashId
      type: string
      format: UUID
      example: abc1234-5d6e-0a8b-c8d7-3a7706a0c312
    Name:
      title: Name
      pattern: "^[A-Za-z0-9\\s-.():_/]{1,255}$"
      type: string
      description: An official name
    Line:
      title: line
      pattern: "^[A-Za-z0-9\\s-.():_/]{1,255}$"
      type: string
      description: An address line
    Address:
      title: Address
      required:
        - city
        - countryCode
        - line1
        - postalCode
        - state
      type: object
      properties:
        type:
          $ref: '#/components/schemas/AddressType'
        line1:
          $ref: '#/components/schemas/Line'
        line2:
          $ref: '#/components/schemas/Line'
        city:
          $ref: '#/components/schemas/AddressCity'
        state:
          $ref: '#/components/schemas/AddressState'
        countryCode:
          $ref: 'core.yaml#/components/schemas/CountryCode'
        postalCode:
          $ref: '#/components/schemas/PostalCode'
      description: An address details.
